version: "3.2"
services:
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin	
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpidb
      - MYSQL_PASSWORD=glpidb
  glpi:
    build:
        context: .
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
