---
- name: "Apache installation using docker container"
  hosts: all
  
   roles:
      - { role: install_docker}
 
  vars_files:
 
  tasks:
  
      
    - name: ansible create GLPI directory
    file:
      path: /tmp/GLPI
      state: directory
      
   - name: copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /tmp/GLPI/{{ item }}
  loop:
  - docker-compose.yml
  - Dockerfile

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /tmp/GLPI
    files:
    - docker-compose.yml
